### ISSUE TITLE
USER STORY: LOGOUT

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute#13]
As a **user I can log out from my account** so that **nobody else can use my account**

### Acceptance criteria
 -  A logged in user can see the logout link in the sidebar
 - When clicking the button the user Is logged out from the app

### Tasks
 - [x] Add logout link to navbar
 - [x] OnClick the user is logged out
 - [x] Redirect user to home page
