### ISSUE TITLE
VISUAL IDENTITY

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute#2]
Design a visual identity for the page

### Acceptance criteria
 - Choose Fonts
 - Create a Favicon
 - Create a color palette
 - Create a logo

### Tasks
 - [x] Font chosen
 - [x] Favicon created and converted
 - [x] Color palette created
 - [x] Logo created and compressed
