### ISSUE TITLE
REACT DEV ENVIRONMENT

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute#4]
Set up  React (frontend) development environment

### Tasks
 - [x] Create a repository from CI template
 - [x] Create gitpod workspace
 - [x] Install compatible version of Node.js
