### ISSUE TITLE
ROUTING

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute#8]
Create Page Routing

### Tasks
 - [x] Setup react router
 - [x] Add root layout
 - [x] Add error page
 - [x] Add routes
